### PR TITLE
Use ILO to pull fan information

### PR DESCRIPTION
**Pull request by thomaswilbur**
I changed the code so that it no longer pulls CPU temps from the machine but instead talks to ILO to get sensor readings.
This is great for when you are running in a VM in ESXi
To run this, you'll only need sshpass and wget now.

### CODE REVIEW

**Comment by That-Guy-Jack** [comment]
Sorry for the delay Would you be happy if i included your edited code as a separate script just for ESXI users?

**Comment by thomaswilbur** [comment]
Yes, that is perfect

**Comment by thomaswilbur** [comment]
@That-Guy-Jack My version works, I haven't setup a cronjob for this to run. so its manual for now but it still runs.

https://github.com/thomaswilbur/HP-ILO-Fan-Control

**Comment by That-Guy-Jack** [comment]
> @That-Guy-Jack My version works, I haven't setup a cronjob for this to run. so its manual for now but it still runs.
> 
> https://github.com/thomaswilbur/HP-ILO-Fan-Control

Would you be ok if i use your adaptations and add it under its own dir?

**Comment by That-Guy-Jack** [comment]
@thomaswilbur  merged in this [commit](https://github.com/That-Guy-Jack/HP-ILO-Fan-Control/commit/2b3b5a16072a623b560e034300bd228600c28f07)

Thanks for making this its been on my list of things to finish


tagging users from original issue:

@supajason

@divadiow

@moni11811

**Comment by That-Guy-Jack** [comment]
Forgot to click close with comment :|

**Pull request closed without merging**
